# Generated by Django 5.1.7 on 2025-03-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monthly_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('stripe', 'Stripe')], max_length=50)),
                ('auth_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='slack_auth.organization')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'unique_together': {('organization', 'integration_type')},
            },
        ),
    ]
